# Generated by Django 3.2.6 on 2021-08-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leocodersapp', '0003_auto_20210831_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='patient_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'timeslot')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
