# Generated by Django 3.2.6 on 2021-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leocodersapp', '0006_alter_schedule_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('symbole', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('adjclose', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'timeslot', 'name')},
        ),
    ]
